# Generated by Django 5.2.3 on 2025-07-28 11:47

import django.utils.timezone
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A descriptive title for the photo', max_length=200)),
                ('image', models.ImageField(help_text='Upload a training photo', upload_to=pages.models.training_photo_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this photo from the training page')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Training Photo',
                'verbose_name_plural': 'Training Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
