# Generated by Django 5.2.4 on 2025-08-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_trainingphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingPhoto',
        ),
    ]
