# Generated by Django 5.2.3 on 2025-07-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin', '0001_initial'),
    ]

    operations = [
    ]
