# Generated by Django 5.2.3 on 2025-07-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionsfootball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='gallery/'),
        ),
    ]
